import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import { useEffect } from "react";

export default function Home() {
  //Importing session
  const { data: session, status } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Authentication app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button
        className="border-4  p-2 rounded-full h-48 w-48 border-green-500 text-white hover:bg-blue-900 "
        onClick={
          () =>
            signIn("google", { callbackUrl: "http://localhost:3000/dashboard" })
          // The signIn function will now exclusively use google aithentication , the callbackUrl is the page you want to redirect after being authenticated.
        }
      >
        Sign in here
      </button>
    </div>
  );
}
